### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'default.xml'

### ISSUE THREAD

**Issue by HiraiKyo** [CA-Giken/rovi_industrial#1]
# エラー内容
```
rosrun rovi_industrial rclient.ur.py
```
を実行すると、
```
FileNotFoundError: [Errno 2] No such file or directory: 'default.xml'
```
のエラーが発生する。

# エラーログ
```
ros@ros-Z790M-ITX-WiFi:~/catkin_ws/src$ rosrun rovi_industrial rclient_ur.py 
get_param exception: ('/config/rsocket',)
rclient_ur:: 127.0.0.1
Traceback (most recent call last):
  File "/home/ros/catkin_ws/src/rovi_industrial/ur/rclient_ur.py", line 55, in <module>
    if not comm.connect(Config['robot_ip'],Config['robot_port'],Config['robot_recipe'],uplink=True):
  File "/home/ros/catkin_ws/src/rovi_industrial/src/rovi_industrial/rtde_sock.py", line 15, in connect
    conf = rtde_config.ConfigFile(xml)
  File "/home/ros/.local/lib/python3.8/site-packages/rtde/rtde_config.py", line 42, in __init__
    tree = ET.parse(self.__filename)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 584, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'default.xml'
```

# メモ
`comm.connect`でファイル名を渡しているが、`comm`は別パッケージにあるのでファイル名ではなくパスオブジェクトで渡さないとエラーになるのでは？

**Comment by KazukiHiraizumi** [comment]
default.xmlのパスが要りそう。
launchの中では、paramにパスをセットして起動してます。
~~~
  <node pkg="rovi_industrial" type="rclient_ur.py" name="" output="screen" respawn="true" respawn_delay="5">
    <param name="/config/rsocket/robot_recipe" value="$(find rovi_industrial)/ur/default.xml" type="str"/>
  </node>
~~~
rosrunだと、ur/にcdしてから起動するか、起動前にparamを↑と同様に設定すればいい。
~~~
rosparam set /config/rsocket/robot_recipe $(rospack find rovi_industrial)/ur/default.xml
~~~
launchの中ではrospackは省略できるが、コマンドラインではコマンド名が要る。

**Comment by HiraiKyo** [comment]
直りました、ありがとう
